SELECT A.PRODUCT_CODE, (SUM(B.SALES_AMOUNT) * A.PRICE) AS SALES FROM PRODUCT A JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE, A.PRICE
ORDER BY (SUM(B.SALES_AMOUNT) * A.PRICE) DESC, PRODUCT_CODE ASC