SELECT FISH.ID, NAME.FISH_NAME, FISH.LENGTH
FROM FISH_INFO FISH JOIN FISH_NAME_INFO NAME ON FISH.FISH_TYPE = NAME.FISH_TYPE
WHERE FISH.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO FISH2
    WHERE FISH.FISH_TYPE = FISH2.FISH_TYPE
)
ORDER BY FISH.ID ASC